# Generated by Django 4.2.3 on 2023-08-11 06:48

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_postmodel_publish_alter_postmodel_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="author_email",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[post.models.validate_author_email],
            ),
        ),
    ]
