# Generated by Django 4.2.3 on 2023-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_postmodel_author_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
